Repository 66yurimi99/DriverMonitoring_AutoDriving, pull requests merged in 2023-10, with the labels that each got.

#9 Lane detection 기능 추가
  Codes/Car/LaneDetection_nayeong.cpp
  Codes/Car/LaneDetection_youngmoon.cpp
  Codes/Car/LaneDetection_youngsik.cpp
  Codes/Car/LaneDetection_yurim.cpp
  Codes/Car/main.cpp
Labels: ✨ feature

#15 [Update] exception handle
  Codes/Driver/ISP.cpp
  Codes/Driver/ISP.h
  Codes/Driver/main.cpp
Labels: ⛏ refactoring

#17 Lane Detection 테스트코드 - 이미지 전처리
  Codes/Car/Test_PreprocessFrame.cpp
Labels: ✅ test

#18 LaneDetection - 이미지 전처리 함수 추가
  Codes/Car/4_PreprocessFrame.cpp
Labels: ⛏ refactoring
